### PR TITLE
Go modules

### PR DESCRIPTION
**Pull request by alexsomesan**
This change transitions the repository to using Go modules for dependency management.
This is a prerequisite for the migration to Terraform 0.12.x.

### CODE REVIEW

**Comment by alexsomesan** [comment]
Fixes #199

**Review by meyskens — APPROVED** [review]
Surprised that this works given all the dep trouble!

**Comment by alexsomesan** [comment]
Actually, me too :)
I've tried a while back and failed to get it working. Now I tried harder :)

**Review by appilon — APPROVED** [review]

**Comment by meyskens** [comment]
@alexsomesan missed this in the giant diff but you forgot to remove the glide and glide lock files

**Comment by alexsomesan** [comment]
Yeah, thanks for pointing that out. I do need to align the vendored K8S packages to the old versions too. I'll follow up with a PR soon.

**Pull request merged**
