### PR TITLE
Upgrade Helm to v2.15.1 and Kubernetes to v1.15.5

### PR DESCRIPTION
**Pull request by JulienBreux**
Hello world 👋

I think that's requested soon by the community.

Here, two upgrades :
* [Helm v2.15.1](https://github.com/helm/helm/releases/tag/v2.15.1)
* [Kubernetes 1.15.5](https://github.com/kubernetes/kubernetes/releases/tag/v1.15.5)

---

## Note

With the new version of Kubernetes, I must use `replace` 😒
If you've a better way, I'll take it with pleasur 🤗 

Sorry for big `vendor/` changes apply by `go mod vendor`.

---

## Info

Others PR to adapt Helm v3 and Kubernetes v1.16.x later. 😉

### CODE REVIEW

**Comment by JulienBreux** [comment]
✅CI 🎉 
/cc @meyskens

**Comment by JulienBreux** [comment]
🔗 Related to https://github.com/terraform-providers/terraform-provider-helm/pull/356 ready to Go 1.13

**Comment by aeneasr** [comment]
Helm 2.15.1 was released today, which includes some bug fixes - can we bump this straight away to that version?

**Comment by JulienBreux** [comment]
@aeneasr 🚀

**Comment by zzzuzik** [comment]
@aeneasr could you please merge it and cut of the new release. we are on 1.16.x and waiting for this fix

**Comment by aeneasr** [comment]
You're pinging the wrong person

**Comment by zzzuzik** [comment]
@aeneasr sorry for that :)
@meyskens @rporres @alexsomesan could you review the PR please

**Review by meyskens — APPROVED** [review]

**Comment by meyskens** [comment]
Looking good here! 
Thanks for the PR!
Will ping @alexsomesan for a release

**Pull request merged**
