### PR TITLE
helm_release: add values_sensitive attribute and cloak values

### LINKED ISSUE #546: Add ability to handle sensitive yaml input without leaking sensitive data
### Description

Currently, the only way to pass in yaml formatted input is through the `values` attribute which will expose any sensitive data through the `metadata.values` output attribute on the `helm_release` resource. I desire a similar `values_sensitive` attribute (like `set_sensitive`) whose values will be cloaked in any console output (exactly how `set_sensitive` does so after #480).

 My use case is to input sensitive values that are outside of our control (passwords controlled by external parties) through a "secure file" in an Azure Devops pipeline. Secondarily, I want the flexibility to template various other (terraform managed) secrets into a yaml file using the `templatefile` function (as I find the number of `set_sensitive` blocks that would be required to be prohibitively time consuming to create and maintain). 

Again, while it would be _possible_ to prevent these values from leaking using `set_sensitive`, when building enterprise software with many secrets (at varying depths in the yaml values structure) this becomes prohibitively complex and time consuming.

Also, I am willing to give implementing this a shot (would be my first contribution using Go, but seems pretty straightforward).

### Potential Terraform Configuration

```hcl
resource "helm_release" "example" {
  name  = "example"
  chart = "example"

  values = [
<<-EOT
notSecret: "not-a-secret-value"
EOT
]

/* 
any keys used in this section will not be leaked in plan/apply through
the output metadata.values or the values_sensitive attribute itself
*/
values_sensitive = [
file("secureFile.yaml"), /* beware, contains secrets */
templatefile("values.template.yaml", { super_secret = var.super_secret }),
<<-EOT
mySecret: "${ var.super_secret_value }"
maybeASecret: "${ var.maybe_not_secret_value }"
EOT
]
}
```

### References

#480 (I am suggesting a new attribute that is a combination of functionality offered through `set_sensitive` and the existing `values` attributes)
#340 (Rejected in favor of 480)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by mcpappas**
### Description

In order to provide a mechanism for accepting sensitive input to a `helm_release` in yaml format (as described in #546) , the `values_sensitive` attribute was added and its keys are cloaked in metadata.values similarly to `set_sensitive` (changed in #480).

The `values_sensitive` attribute functions just like the `values` attribute, just with the addition of cloaking any keys that `values_sensitive` creates in the `metadata.values` attribute.

(This is my first experience with Go, but I tried to match the style and patterns in surrounding code. I know I still need to implement acceptance tests, but figured I would get the functional bits out there for feedback.)

### Acceptance tests
- [ ] Have you added an acceptance test for the functionality being added?
- [ ] Have you run the acceptance tests on this branch? (If so, please include the test log in a gist)

### References

Resolves #546.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### CODE REVIEW

**Comment by mcpappas** [comment]
@dak1n1, I just realized I never got this one over the finish line. Let me know if there is anything you need me to fix/change.

**Comment by jeff-jk** [comment]
Any update here?

**Comment by victorgetz** [comment]
Any news regarding this topic we need this feature also

**Comment by idan-gur** [comment]
Same, can this get merged?

**Comment by hilariocoelho** [comment]
> Same, can this get merged?

#625 includes the same feature but with tests and documentation. I think this PR should be closed and the other one merged.
@dak1n1

**Pull request closed without merging**
