### PR TITLE
Upgrade to go v1.13

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by chenrui333** [comment]
```
$ make test
==> Checking that code complies with gofmt requirements...
go test "./helm" || exit 1
go: finding github.com/hashicorp/terraform-plugin-sdk v1.1.0
go: finding k8s.io/api v0.0.0-20190409021203-6e4e0e4f393b
go: finding github.com/Azure/go-autorest v11.1.0+incompatible
go: finding github.com/gophercloud/gophercloud v0.4.0
go: finding golang.org/x/net v0.0.0-20191002035440-2ec189313ef0
go: finding golang.org/x/sys v0.0.0-20191002091554-b397fe3ad8ed
go: finding k8s.io/cli-runtime v0.0.0-20190409023024-d644b00f3b79
go: finding github.com/Masterminds/sprig v2.18.0+incompatible
go: finding k8s.io/apiextensions-apiserver v0.0.0-20190409022649-727a075fdec8
go: finding google.golang.org/genproto v0.0.0-20190927181202-20e1ac93f88c
go: finding k8s.io/kubernetes v1.14.1
go: finding k8s.io/apiserver v0.0.0-20190409021813-1ec86e4da56c
go: finding k8s.io/cloud-provider v0.0.0-20190409023720-1bc0c81fa51d
go: finding gopkg.in/yaml.v1 v1.0.0-20140924161607-9f9df34309c0
ok  	github.com/terraform-providers/terraform-provider-helm/helm	0.315s
echo "./helm" | \
		xargs -t -n4 go test  -timeout=30s -parallel=4
go test -timeout=30s -parallel=4 ./helm
ok  	github.com/terraform-providers/terraform-provider-helm/helm	0.240s```

**Comment by chenrui333** [comment]
https://github.com/kubernetes/website/pull/15667

>  It is recommended to use the apt installation of docker from ([Docker](https://www.docker.com/products/docker-desktop), when using the none driver. The snap installation of docker does not work with minikube.

**Review by JulienBreux — APPROVED** [review]

**Comment by meyskens** [comment]
@chenrui333 can you get me more context on the Docker change? As far as I know Travis CI does not use snap to install anything.

**Comment by chenrui333** [comment]
@meyskens Travis does use snap though, but I can certainly remove the `service: docker` declaration.

I thought we need docker, I guess I might be wrong.

For the snap support, here is the doc, https://blog.travis-ci.com/2019-06-21-snaps-support-travis-ci

**Review by JulienBreux — APPROVED** [review]

**Comment by meyskens** [comment]
@chenrui333 we do need Docker but it comes pre-installed inside Travis (and not using snap as far as I know, the blogpost doesn't mention snap being the new default mode to install it)
Installing it via apt on top of what is there adds an extra minute of CI time.

**Review by alexsomesan — APPROVED** [review]
CI green. LGTM

**Pull request merged**
