### PR TITLE
feat: support kubeconfig passed as string

### PR DESCRIPTION
**Pull request by krzysztof-miemiec**
# Description

I use `terraform-aws-eks` module, which provides convenient output of `kubeconfig` which I can save as Terraform output, or pass further. This PR allows to pass `kubeconfig` contents to provider, as below:

```tf
variable "cluster_id" {
  type        = string
  description = "EKS Cluster ID used to configure Helm & Kubernetes providers."
}

data "aws_eks_cluster" "cluster" {
  name = var.cluster_id
}

data "aws_region" "current" {}

locals {
  # AWS EKS Cluster KubeConfig Sample
  # i.e. `terraform-aws-eks` module has kubeconfig output, which is a string with similar content as below
  kubeconfig = <<-EOF
    apiVersion: v1
    kind: Config
    preferences: {}
    clusters:
    - name: eks-cluster
      cluster:
        certificate-authority-data: ${data.aws_eks_cluster.cluster.certificate_authority.0.data}
        server: ${data.aws_eks_cluster.cluster.endpoint}
    contexts:
    - name: terraform
      context:
        cluster: eks-cluster
        user: terraform
    current-context: terraform
    users:
    - name: terraform
      user:
        exec:
          apiVersion: client.authentication.k8s.io/v1alpha1
          command: aws
          args:
          - --region
          - ${data.aws_region.current.name}
          - eks
          - get-token
          - --cluster-name
          - ${var.cluster_id}
  EOF
}

provider "helm" {
  kubernetes {
    config_content = local.kubeconfig
  }
}
```

This may be a good alternative to a setup like this:
```tf
provider "helm" {
  kubernetes {
    load_config_file       = false
    host                   = data.aws_eks_cluster.cluster.endpoint
    cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
    token                  = data.aws_eks_cluster_auth.cluster.token
  }
}
```

or 
```tf
provider "helm" {
  kubernetes {
    load_config_file       = false
    host                   = data.aws_eks_cluster.cluster.endpoint
    cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
    exec {
      api_version = "client.authentication.k8s.io/v1alpha1"
      args = ["--region", data.aws_region.current.name, "eks", "get-token", "--cluster-name", var.cluster_id]
      command     = "aws"
    }
  }
}
```

### Stuff in this PR:
* `config_content` option added to `kubernetes` provider block
* throw an error if kubeconfig can not be loaded correctly (previously we ended up with segfault in such case, trying to load `ClientConfig` from `nil` object)
* docs that reflect new option
* unfortunately no tests (manually tested new vs old configuration cases)

### Acceptance tests
- [ ] Have you added an acceptance test for the functionality being added?
- [ ] Have you run the acceptance tests on this branch? (If so, please include the test log in a gist)

From what I see, there are no acceptance tests made for provider's configuration. I manually tested my changes for two cases:
- I ran new build against old configuration (using host, cluster ca & token) 
- I ran new build against new configuration (passed `kubeconfig` to `config_content`)

### References

* https://github.com/hashicorp/terraform-provider-helm/issues/508

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### CODE REVIEW

**Comment by aareet** [comment]
Hi @krzysztof-miemiec, thanks for this. Generally we recommend using a local_file resource for this functionality - can you tell us a bit about why this solution is required and in what way local_file is lacking in your use case?

**Comment by krzysztof-miemiec** [comment]
@aareet I don't commit kubeconfig to my infra repositories (should I?) and Terraform would always report changes if I used local_file. I'd see this PR as a way to avoid creation of local_file and directly pass kubeconfig contents to provider. For now, I can use locals block to `yamldecode` kubeconfig output from AWS EKS Terraform module and pass that to a few separate fields.

**Comment by alexsomesan** [comment]
@krzysztof-miemiec Out of curiosity, why is using the `exec` block in the provider configuration not a better option for you?
Like you already mentioned, you can do:
```
provider "helm" {
  kubernetes {
    load_config_file       = false
    host                   = data.aws_eks_cluster.cluster.endpoint
    cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
    exec {
      api_version = "client.authentication.k8s.io/v1alpha1"
      args = ["--region", data.aws_region.current.name, "eks", "get-token", "--cluster-name", var.cluster_id]
      command     = "aws"
    }
  }
}
```

**Comment by krzysztof-miemiec** [comment]
@alexsomesan after I created this PR, I realized that I can make use of `exec`, however passing multiple fields to Kubernetes/Helm providers at all times time is rather WET than DRY (I'd be glad if you could recommend something if there's a better way to manage multi-config setups). Now, I feel it may not be a good idea to clutter K8s-related providers with additional fields and that my PR is just a small improvement for ~4 people including myself, rather than a totally new feature (initially I somehow missed the fact that `exec` can be passed to providers). 🤔 

My current setup (see below) is as reusable as I could make it, but it requires Terragrunt (with pure Terraform it would be a bit harder to pass values between separate configurations).

parts of `cluster` component (`main.tf` and `variables.tf`):
```
locals {
  kubernetes_config = {
    host                   = module.eks.cluster_endpoint
    cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)
    exec = {
      api_version = "client.authentication.k8s.io/v1alpha1"
      command     = "aws"
      args = [
        "--region", data.aws_region.current.name,
        "eks", "get-token",
        "--cluster-name", local.cluster_name
      ]
      env = {
        AWS_PROFILE = var.aws_profile
      }
    }
  }
}

output "kubernetes_config" {
  value       = local.kubernetes_config
  sensitive   = true
  description = "Kubernetes config. You can pass it to Kubernetes or Helm Providers to authenticate without kubeconfig."
}
```


`terragrunt.hcl`:
```
terraform {
  source = "../../components/kubernetes-service"
}

include {
  path = find_in_parent_folders()
}

dependency "cluster" {
  config_path = "../cluster"
}

generate "kubernetes-config" {
  path           = "generated-kubernetes.config.tf"
  comment_prefix = "#"
  if_exists      = "overwrite_terragrunt"
  contents       = file("../kubernetes.config.tf")
}

inputs = {
  kubernetes_config = dependency.cluster.outputs.kubernetes_config
}

```

`kubernetes.config.tf`:
```tf
# --------------------------------------------------------
# INPUT VARIABLES
# Safe defaults should be set in `terragrunt.hcl` file
# Values can be overridden with local terraform.tfvars
# --------------------------------------------------------

variable "kubernetes_config" {
  type = object({
    host                   = string
    cluster_ca_certificate = string
    exec = object({
      api_version = string
      command     = string
      args        = list(string)
      env         = map(string)
    })
  })
  description = "Kubernetes configuration. Used by Kubernetes and Helm Providers to authenticate without kubeconfig."
}

# --------------------------------------------------------
# PROVIDERS
# Safe defaults should be set in `terragrunt.hcl` file
# Values can be overridden with local terraform.tfvars
# --------------------------------------------------------

provider "kubernetes" {
  version = "~> 1.12"

  load_config_file       = false
  host                   = var.kubernetes_config.host
  cluster_ca_certificate = var.kubernetes_config.cluster_ca_certificate
  exec {
    api_version = var.kubernetes_config.exec.api_version
    command     = var.kubernetes_config.exec.command
    args        = var.kubernetes_config.exec.args
    env         = var.kubernetes_config.exec.env
  }
}

provider "helm" {
  version = "~>1.2.4"

  kubernetes {
    load_config_file       = false
    host                   = var.kubernetes_config.host
    cluster_ca_certificate = var.kubernetes_config.cluster_ca_certificate
    exec {
      api_version = var.kubernetes_config.exec.api_version
      command     = var.kubernetes_config.exec.command
      args        = var.kubernetes_config.exec.args
      env         = var.kubernetes_config.exec.env
    }
  }
}
```

**Comment by iBrandyJackson** [comment]
hi @krzysztof-miemiec thanks again for this contribution! However, as stated above, using the exec block in the provider configuration is a better solution to this PR. In an effort to clean up our open PRs we will be closing this PR. This helps our maintainers find and focus on the active issues. 

If you have found a problem that seems related to this change, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further.

**Pull request closed without merging**
