### PR TITLE
remove usage of config pkg

### PR DESCRIPTION
**Pull request by appilon**
In preparation for the upcoming standalone SDK. We are removing the usage of a few removed/deprecated functions and packages. Upgraded terraform to v0.12.8

### CODE REVIEW

**Review by radeksimko — APPROVED** [review]
(nitpick; for next time) it would be great to keep dependency changes in a separate commit.

**Comment by appilon** [comment]
seems like acceptance tests are broken on master

**Comment by alexsomesan** [comment]
There was a problem with the CI configuration (outdated parameters).
Tests in master are passing (now in CI too).

**Review by alexsomesan — APPROVED** [review]
Looks good to me.
CI is green.

**Pull request merged**
