### PR TITLE
metadata values can sometimes be sensitive due to the usage of set_sensitive

### LINKED ISSUE #251: Sensitive Values leak when changed/removed
### Terraform Version
```
Terraform v0.11.7
```

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "thanos" {
  name       = "thanos"
  repository = "${var.helm_repo}"
  chart      = "thanos"
  version    = "0.2.0"
  namespace  = "${module.prometheus.namespace}"

  set_sensitive {
    name  = "s3.awsAccessKey"
    value = "access key"
  }
  set_sensitive {
    name  = "s3.awsSecretKey"
    value = "secret key"
  }

}
```

### Expected Behavior

Diff not to show sensitive values

### Actual Behavior

Diff showed sensitive values

```
      set_sensitive.#:                "2" => "0"
      set_sensitive.3469752628.name:  "s3.awsSecretKey" => ""
      set_sensitive.3469752628.value: "some_secret_here" => ""
      set_sensitive.4209480927.name:  "s3.awsAccessKey" => ""
set_sensitive.4209480927.value: "other_secret_here" => ""
```

### Steps to Reproduce
1. `terraform apply`
1. Remove `set_sensitive` values
1. `terraform plan`

### Important Factoids

This seems like it would be a terraform bug instead of one in the provider but I figured I would start here first.

### LINKED ISSUE #333: Sensitive values leaked on `terraform plan`
### Terraform Version
0.12.8

### Affected Resource(s)

- helm_release

### Expected Behavior
Sensitive value should be hidden on `terraform plan` / `terraform apply`

### Actual Behavior
Sensitive value echoed on `terraform plan`

### Steps to Reproduce

1. Use helm_release with set_sensitive block.
2. `terraform apply`
3. `terraform plan` echoes back sensitive value in metadata section.

### PR DESCRIPTION
**Pull request by rmb938**
Fixes #251 
Fixes #333

WIP

This doesn't seem to be working on existing resources... weird.

### CODE REVIEW

**Comment by bjaworski3** [comment]
@rmb938 I was able to get a similar change working by changing the entire metadata block to `Sensitive:   true`. I had the same issue as you where if I just changed the `metadata.values` to sensitive, it wouldn't update objects that already existed.

**Comment by derrix060** [comment]
Any plans to merge this?

**Comment by mcristina422** [comment]
I think that this should be merged.

We should either force update (may not be possible) all of the existing `metadata.values` field that keeps leaking secrets. Or should note in the release notes that an update to the resource is necessary to recreate the values as sensitive

**Comment by aareet** [comment]
Closing in favour of https://github.com/terraform-providers/terraform-provider-helm/pull/480

**Pull request closed without merging**
