### PR TITLE
migrate to terraform-plugin-sdk

### PR DESCRIPTION
**Pull request by mcristina422**
This updates the helm provider to use the newly released plugin sdk. https://www.terraform.io/docs/extend/plugin-sdk.html

I used https://github.com/hashicorp/tf-sdk-migrator to complete the migration

There was an incompatibility with `terraform.VersionString()` and I followed the [example](https://github.com/terraform-providers/terraform-provider-kubernetes/pull/620/files)

### CODE REVIEW

**Comment by meyskens** [comment]
Thank you for the PR! It looks very good, just trying to get the acceptance tests to run properly again so I can merge this

**Review by meyskens — APPROVED** [review]

**Comment by meyskens** [comment]
@mcristina422 could you rebase from master to have a fix for the CI?

**Comment by mcristina422** [comment]
Thanks for helping out with the acceptance tests, I was struggling to figure it out!

Rebased and squashed @meyskens

**Comment by meyskens** [comment]
Thanks!

**Pull request merged**
