### PR TITLE
Vendor in Helm 2.11 using Glide

### PR DESCRIPTION
**Pull request by meyskens**
~~PRing this early to see how Travis builds this~~

Motivation for ditching `dep` in 2018: getting kubernetes to work with `dep` is not fun. I picked Glide as this is what Helm uses. Also `dep` is not supported by `client-go` (see https://github.com/kubernetes/client-go/blob/master/INSTALL.md#dep-not-supported-yet) which is due an essential feature missing in `dep`. As this is missing it is vendoring in incorrect versions of non-dep using packages causing a lot of compile errors.

### CODE REVIEW

**Comment by rporres** [comment]
Tested build in Darwin and works fine. I still need to go through acceptance tests, though

**Comment by meyskens** [comment]
Known issues:
- Tiller install goes wrong, needs `kubectl -n kube-system patch deployment tiller-deploy -p '{"spec": {"template": {"spec": {"automountServiceAccountToken": true}}}}'` to patch

**Comment by olib963** [comment]
@meyskens Does the tiller install still not work with helm 2.11? I thought that release allows setting the automount configuration value and defaults to `true`?

I also wanted to test the effects of https://github.com/terraform-providers/terraform-provider-kubernetes/pull/198 as an interim solution, it might work if we define automount at the service account level, haven't had time to test this yet though.

**Comment by meyskens** [comment]
@olib963 I have not yet investigated that as i get weird things with the acceptance tests. My bet is that we set some option incorrect or that there might be an option to do this which is defaulted to `false` in the api

**Comment by olib963** [comment]
@meyskens I think it is [here](https://github.com/terraform-providers/terraform-provider-helm/blob/3e0d3b706a2005301f32d0b7ac1e67cdcfa5880e/helm/provider.go#L401), you should be able to set `AutoMountServiceAccountToken` to be true and that then gets used [here](https://github.com/helm/helm/blob/8be42bae885a04b4acc242cf420911145b32ee1c/cmd/helm/installer/install.go#L222)

It seems like the CLI parser defaults to true but the object itself defaults to false.

**Comment by meyskens** [comment]
@olib963 that's correct, i have done this and it works

**Comment by gaui** [comment]
Can't wait for this and https://github.com/terraform-providers/terraform-provider-kubernetes/pull/198 to get in 🙏 Thank you for your awesome work!

**Comment by Stelminator** [comment]
@meyskens please consider: https://github.com/terraform-providers/terraform-provider-helm/pull/152

**Comment by Stelminator** [comment]
@meyskens thanks for merging!

The remaining `o.AutoMountServiceAccountToken = true` a.k.a. https://github.com/terraform-providers/terraform-provider-helm/pull/143/commits/24909dfa969fa7ee4bd16f98e96831ed2bb4d484 should be removed/reverted.  Otherwise, the parameter I added will have no effect.

Edit: looks like this got cleaned up.  Thanks!

**Comment by schaermu** [comment]
@meyskens is there an ETA for this branch to land on master? i'm asking because we are locked in behind a corporate proxy and are unable to use this vital provider due to the regression described in PR https://github.com/helm/helm/pull/4579.

**Comment by joelchrist** [comment]
Is there anything that's still holding back the merge for this PR? If so, is there anything I can do to speed up the process?

**Comment by gaui** [comment]
We are eagerly waiting for this bug to be fixed. 🙏

**Comment by dongwoo1005** [comment]
Any update on this?

**Comment by olib963** [comment]
Hello all, since about 2 weeks ago a change to the service account resource (https://github.com/terraform-providers/terraform-provider-kubernetes/pull/198) was released in the kubernetes provider 1.4.0. This can act as a work around while this is waiting to be merged i.e. 

```hcl
provider "kubernetes" {
  version                = "1.4.0"
  ... {K8S CONFIG} ...
}

resource "kubernetes_service_account" "tiller" {
  automount_service_account_token = true

  metadata {
    name      = "tiller-service-account"
    namespace = "kube-system"
  }
}

resource "kubernetes_cluster_role_binding" "tiller" {
  metadata {
    name = "tiller-cluster-rule"
  }

  role_ref {
    api_group = "rbac.authorization.k8s.io"
    kind      = "ClusterRole"
    name      = "cluster-admin"
  }

  subject {
    kind      = "ServiceAccount"
    name      = "${kubernetes_service_account.tiller.metadata.0.name}"
    api_group = ""
    namespace = "${kubernetes_service_account.tiller.metadata.0.namespace}"
  }
}

provider "helm" {
  version = "0.6.2"

  service_account = "${kubernetes_service_account.tiller.metadata.0.name}"

  kubernetes {
      ... {K8S CONFIG} ...
  }
}
```

will now work with RBAC clusters. Hopefully this helps and alleviates some of the pressure of merging this in.

**Comment by vranystepan** [comment]
@olib963 You're my hero! 

It's also a good idea to put some dependencies in place so SA and Binding don't get destroyed before the release. Otherwise decommissioning fails.

```hcl
resource "helm_release" "my_database" {
    name      = "blahblah"
    chart     = "./chart"
    depends_on = [
      "kubernetes_cluster_role_binding.tiller", 
      "kubernetes_service_account.tiller"
    ]
}
```

**Comment by meyskens** [comment]
Just a small update: I am working on fixing the acceptance tests. Since this is a big change we want to have a proper testing system working to tell us if there are any issues with this.

**Comment by HarithJ** [comment]
Hello @meyskens,
I am running Terraform version 0.11.11 together with version 0.8.0 of Helm provider, and I am still getting this error:
`helm_release.nginx-ingress: Get https://XX.XXX.XX.X/apis/extensions/v1beta1/namespaces/kube-system/deployments/tiller-deploy: dial tcp XX.XXX.XX.X:443: connect: connection refused`

Can you please help me out?

Here is how I have configured Helm provider:

```
provider "kubernetes" {
  host     = "${var.cluster-host}"
  username = "${var.cluster-username}"
  password = "${var.cluster-password}"

  client_certificate     = "${base64decode(var.cluster-client-cert)}"
  client_key             = "${base64decode(var.cluster-client-key)}"
  cluster_ca_certificate = "${base64decode(var.cluster-ca-certificate)}"
}

resource "kubernetes_service_account" "tiller" {
  metadata {
    name      = "tiller"
    namespace = "kube-system"
  }
}

resource "kubernetes_cluster_role_binding" "tiller" {
  metadata {
    name = "tiller"
  }

  role_ref {
    api_group = "rbac.authorization.k8s.io"
    kind      = "ClusterRole"
    name      = "cluster-admin"
  }

  subject {
    api_group = ""
    kind      = "ServiceAccount"
    name      = "tiller"
    namespace = "kube-system"
  }
}

provider "helm" {
  install_tiller  = true
  service_account = "tiller"
  namespace       = "kube-system"
  kubernetes {
      host     = "${var.cluster-host}"
      username = "${var.cluster-username}"
      password = "${var.cluster-password}"

      client_certificate     = "${base64decode(var.cluster-client-cert)}"
      client_key             = "${base64decode(var.cluster-client-key)}"
      cluster_ca_certificate = "${base64decode(var.cluster-ca-certificate)}"
  }
}
```

**Pull request merged**
