### PR TITLE
Remove ForceNew on repo and chart changes

### LINKED ISSUE #173: New resource shouldn't be required when a chart is updated
Seem like this issue somehow resurfaced again

https://github.com/terraform-providers/terraform-provider-helm/issues/32

### PR DESCRIPTION
**Pull request by lawliet89**
Fixes #173

`helm upgrade` does not delete the release when the chart/repo are changed. The Helm provider should not too.

I tested this by changing a chart/repo and the upgrade worked fine.

### CODE REVIEW

**Comment by lawliet89** [comment]
@rporres @meyskens  Any thoughts on this other than radio silence?

**Comment by legal90** [comment]
@rporres @meyskens Could you please review this PR?

**Comment by legal90** [comment]
@rporres @meyskens @alexsomesan  Could anyone review this PR and provide the feedback? 

IMO, it totally makes sense to remove `ForceNew` flag from `chart` and `repository` parameters, since helm handles such updates of existing releases.

**Comment by Starefossen** [comment]
We have been hit hard by this one lately. Anything we can do to help moving this forward?

**Review by Starefossen — APPROVED** [review]

**Comment by rporres** [comment]
Apologies, this had fallen off my radar. Makes total sense.

**Pull request merged**
