### PR TITLE
Fix nil path for dependency_update flag

### LINKED ISSUE #459: dependency_update doesn't act as expected
### Terraform Version
Terraform v0.12.21
+ provider.aws v2.55.0
+ provider.helm v1.1.1
+ provider.kubernetes v1.11.1
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
+ provider.vault v2.9.0

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "nginx-ingress-controller" {
  name      = "my-nginx-ingress-controller"
  chart       = "charts/my-nginx-ingress-controller"
  namespace = "kube-system"

  dependency_update = true
}
```

The Chart.yaml
```yaml
apiVersion: v1
name: my-nginx-ingress-controller
version: 1.0.0
dependencies:
  - name: nginx-ingress
    version: 1.34.3
    repository: "@stable"
```

### Debug Output
https://gist.github.com/IlyaKochnev/b239856bfb923896130119eb481f32cc

### Expected Behavior
In accordance with https://www.terraform.io/docs/providers/helm/r/release.html#dependency_update Terraform must update dependencies and successfully install the chart.

### Actual Behavior
Terraform produces the error:
```
helm_release.nginx-ingress-controller: Creating...
Error: could not find : stat : no such file or directory
  on main.tf line 97, in resource "helm_release" "nginx-ingress-controller":
  97: resource "helm_release" "nginx-ingress-controller" {
```
There is no visible signs of dependency downloading.
After `helm dep update` run manually, Terraform installs the chart without any issues.

### Steps to Reproduce
1.  Prepare a simple chart, like
```yaml
apiVersion: v1
name: my-nginx-ingress-controller
version: 1.0.0
dependencies:
  - name: nginx-ingress
    version: 1.34.3
    repository: "@stable"
```
2. Prepare a terraform code to deploy the chart with Helm, see example above
3. `terraform apply`

### Important Factoids
helm version
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

### PR DESCRIPTION
**Pull request by rvichery**
### Description

This PR addresses issue #459 where dependency_update fails when using a local chart. As commented, the path injected for updating dependency is always `nil`. This PR corrects the mistake by correctly reassigning the `path` variable within `getChart`. 

To make sure the issue was fixed, I added an acceptance test using an example local chart (`helm/local-chart`).

Here is the test output before fixing the issue:
https://gist.githubusercontent.com/rvichery/304580c7cf0c48955f3e81455cbf1af0/raw/edc389eac61ef7b234232aca9d8431104eccc23a/after-fix

Here is the test output after fixing the issue:
https://gist.githubusercontent.com/rvichery/304580c7cf0c48955f3e81455cbf1af0/raw/edc389eac61ef7b234232aca9d8431104eccc23a/after-fix

### Acceptance tests
- [x] Have you added an acceptance test for the functionality being added?
- [x] Have you run the acceptance tests on this branch? (If so, please include the test log in a gist)

Full acceptance test output:
https://gist.githubusercontent.com/rvichery/304580c7cf0c48955f3e81455cbf1af0/raw/edc389eac61ef7b234232aca9d8431104eccc23a/complete-test-acceptance-after-fix

### References

Fixes #459

### CODE REVIEW

**Comment by rvichery** [comment]
Moved the test chart under the new `test-fixtures` directory and rebased on top of current master has the PR had conflicts with recent changes. Please let me know if there is anything I need to do to get that PR reviewed and merged.

**Comment by rvichery** [comment]
@aareet should I tag somebody to review this PR ? Thanks.

**Comment by aareet** [comment]
No need to tag someone @rvichery , we appreciate the contribution. It's in our queue for triage and review -> https://github.com/terraform-providers/terraform-provider-helm/blob/master/_about/PULL_REQUESTS.md#pull-request-lifecycle

**Comment by koxu1996** [comment]
Any ETA?

**Review by jrhouston — APPROVED** [review]
Thank you for fixing this @rvichery and for adding an acceptance test, this looks good! 🚀

**Pull request merged**
