### PR TITLE
Release diff

### PR DESCRIPTION
**Pull request by gordonbondon**
### Description

`helm-diff` already does a really good job at diffing helm releases, so I wanted to give a try integrating it with this provider. Her's what it looks like during `plan` or `apply`:

* when updating chart version and some values:
Screenshot 2020-07-21 at 23 03 53

* when adding new secret:
Screenshot 2020-07-21 at 23 19 10

* when changing secret value
Screenshot 2020-07-21 at 23 19 45

for newly added resource:
Screenshot 2020-07-24 at 18 59 47

This will also help with catching updates in local charts #515 since diff will detect a change in rendered templates, and terraform will reapply them.

There are a couple of issues I wanted to discuss:

1. Unfortunately `helm-diff` depends on helm2. But if this approach seems like a good idea I think it would be possible to extract diffing in a separate package, so we can remove this dependency.
2. Currently, it runs diff only for chart changes, but I think it will be possible to get live resource manifests and feed them into `diff.Releases` to be able to detect manual changes as discussed in #444
3. helm-diff has a lot of options - like suppressing certain api kinds, or size of diff context - we can expose these options. Proposed config section:

    ```hcl
    release_diff {
      enabled = true # false by default
      suppress_secrets = true # true by default
      supress_kinds = ["ConfigMap", "Service"]
      no_hooks = true
      include_tests = false
      context = 5
      diff = <-EOF
		here goes computed diff
      EOF
    }
    ```

4. If we have both serverside diff and release template diff, should we expose both separately, or stick with just serverside diff as the most meaningful?

If this seems like a good idea overall I'll continue working on adding tests and trying to add serverside change detection.

### Acceptance tests
- [ ] Have you added an acceptance test for the functionality being added?
- [ ] Have you run the acceptance tests on this branch? (If so, please include the test log in a gist)

### References

#79 
#444
#515

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### CODE REVIEW

**Comment by aareet** [comment]
Thanks for this prototype @gordonbondon - we're planning to investigate if supporting diffs is possible and how best to implement it this quarter (https://github.com/hashicorp/terraform-provider-helm/blob/master/_about/ROADMAP.md). When we get to evaluating our options, we'll take a look at this PR and share our thoughts on your suggestion.

**Comment by ksvladimir** [comment]
Our team would love to see this happen! We're evaluating terraform vs. competition and it's a major point in our discussions.

**Comment by ivanilves** [comment]
This is such an awesome and needed feature :pray: 

Any updates on this being incorporated into Helm provider @aareet ? :slightly_smiling_face: 

Thank you!

**Comment by mnaser** [comment]
@gordonbondon do you have some spare time to rebase this (and maybe hopefully sign the CLA as well?)

**Comment by gordonbondon** [comment]
This PR can't be merged as is even after rebase, and would require a lot more fixes to make it work properly. 

Besides, I think there's now a better approach of doing this based on https://github.com/bacongobbler/helm-patchdiff (see discussion here https://github.com/databus23/helm-diff/issues/176 and here https://github.com/helm/helm/issues/8718)

**Comment by llamahunter** [comment]
> This PR can't be merged as is even after rebase, and would require a lot more fixes to make it work properly.
> 
> Besides, I think there's now a better approach of doing this based on https://github.com/bacongobbler/helm-patchdiff (see discussion here [databus23/helm-diff#176](https://github.com/databus23/helm-diff/issues/176) and here [helm/helm#8718](https://github.com/helm/helm/issues/8718))

What's the plan to implement a helm diff in the terraform provider? The opacity of the current helm provider plan is a problem for us.

**Comment by redeux** [comment]
@llamahunter We're actively investigating this feature and should be in a position to share an update soon.

**Comment by sherifabdlnaby** [comment]
Please make this possible 🙏🏻  would be glad to contribute if help is needed.

**Comment by jrhouston** [comment]
Thanks for the community support for this feature everyone. We have decided to go in a slightly different direction from this PR as some new developments over the last year have made it more feasible to create a diff experience that is more native to Terraform, i.e you see the diff as HCL in the plan and not as a separate YAML diff.

I have opened a draft PR here so you can preview: https://github.com/hashicorp/terraform-provider-helm/pull/702

Thank you @gordonbondon for doing the ground work on this feature – I have added you as a co-author in the PR I linked above.

**Pull request closed without merging**
