### PR TITLE
Upgrade to helm 3.3.4

### LINKED ISSUE #571: Update Helm to 3.3.1
### Description

There is a known issue with older versions of Helm and Kubectl where they will hang when processing large nested CRD's. This is impacting deployment of charts such as cert-manager. 

The Helm library should be updated to the 3.3.1 release.

### References
https://github.com/kubernetes/kubernetes/issues/91615
https://github.com/hashicorp/terraform-provider-helm/issues/570

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by mcfedr**
### Description

Upgrade to helm 3.3

### Acceptance tests
- [x] Have you added an acceptance test for the functionality being added?
- [x] Have you run the acceptance tests on this branch? (If so, please include the test log in a gist)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### CODE REVIEW

**Comment by sam-cogan** [comment]
Would be good to bump this to 3.3.1 to fix https://github.com/hashicorp/terraform-provider-helm/issues/571

**Comment by mcfedr** [comment]
i see the tests are failing but this seems to be an issue for all PRs at the moment

**Comment by js-timbirkett** [comment]
I think that they're failing due to the upstream `terraform-website` tests failing. Maybe remove website tests for now?

**Comment by js-timbirkett** [comment]
@jrhouston @dak1n1 - Hi John and Stef 👋 

I don't normally reach out directly to maintainers like this but this PR (or rather the bugs in earlier Kubernetes and Helm versions) is a blocker for deploying some Helm charts like `cert-manager v1.0.1`. I saw that you were able to help with the last Helm dependency upgrade and hoped you might be able to help out in getting this PR reviewed and progressed?

Thanks, Tim.

**Comment by horjulf** [comment]
`3.3.2` was released today.

https://github.com/helm/helm/releases/tag/v3.3.2

**Comment by mcfedr** [comment]
Updated the dependency to 3.3.2

**Comment by andyspiers** [comment]
@js-timbirkett @mcfedr - i've opened a complimentary PR https://github.com/hashicorp/terraform-provider-helm/pull/590 which fixes the website tests, hopefully if that gets merged it will enable the acceptance tests to run for this PR

**Comment by sam-cogan** [comment]
Can this be made a priority to get merged? It is blocking some deployment of some fairly critical helm charts

**Comment by mcfedr** [comment]
`make testacc` - https://gist.github.com/mcfedr/64376294e3f583d77147edb2d888e42f

**Comment by aareet** [comment]
Thanks for keeping this PR updated - we are planning to push a helm upgrade as a part of some other changes, that's why the wait. Appreciate your patience!

**Comment by sennerholm** [comment]
The #590 (website tests) is now merged, is it worth to rerun the tests to see if it's getting green? Or is that colliding with the big plan @aareet ?

/Another user really want this is in a released version of the provider

**Comment by mcfedr** [comment]
@sennerholm Just rebased on master so maybe the tests will show as green now

**Review by sebglon — APPROVED** [review]
LGTM

**Review by jrhouston — APPROVED** [review]
Thanks for taking care of this @mcfedr!

Thanks for waiting everyone. 🚀

**Comment by sleenen** [comment]
Happy this is merged, can we expect a new release to go with this too?

**Comment by sennerholm** [comment]
@sleenen , I don't know if you have seen it yet, but https://github.com/hashicorp/terraform-provider-helm/releases contains part of a 1.3.1 release and 
```
terraform providers mirror ~/.terraform.d/plugins
- Mirroring hashicorp/helm...
  - Selected v1.3.1 to meet constraints ~> 1.3
  - Downloading package for darwin_amd64...
  - Package authenticated: signed by HashiCorp
```

**Comment by sleenen** [comment]
thank you @sennerholm ! I have seen it, tried it right away, everything working like a charm (needed this for installing cert-manager latest version, which required higher helm version)

**Pull request merged**
