### PR TITLE
Resolving tfproviderlint issues

### LINKED ISSUE #533: Evaluate linter errors
Evaluate and fix linter errors generated by https://github.com/bflad/tfproviderlint

### Debug Output

```
❯ tfproviderlint ./...
/Users/aareet/go/src/github.com/aareet/terraform-provider-helm/helm/data_repository_test.go:11:28: AT001: missing CheckDestroy
/Users/aareet/go/src/github.com/aareet/terraform-provider-helm/helm/resource_release_test.go:343:36: AT001: missing CheckDestroy
/Users/aareet/go/src/github.com/aareet/terraform-provider-helm/helm/resource_release_test.go:370:36: AT001: missing CheckDestroy
/Users/aareet/go/src/github.com/aareet/terraform-provider-helm/helm/resource_release_test.go:400:36: AT001: missing CheckDestroy
/Users/aareet/go/src/github.com/aareet/terraform-provider-helm/helm/resource_release_test.go:424:36: AT001: missing CheckDestroy
/Users/aareet/go/src/github.com/aareet/terraform-provider-helm/helm/resource_release_test.go:453:36: AT001: missing CheckDestroy
/Users/aareet/go/src/github.com/aareet/terraform-provider-helm/helm/resource_repository_test.go:16:28: AT001: missing CheckDestroy
/Users/aareet/go/src/github.com/aareet/terraform-provider-helm/helm/resource_release_test.go:61:6: AT002: acceptance test function name should not include import
/Users/aareet/go/src/github.com/aareet/terraform-provider-helm/helm/resource_release.go:1017:9: R001: ResourceData.Set() key argument should be string literal
/Users/aareet/go/src/github.com/aareet/terraform-provider-helm/helm/resource_release.go:58:3: R003: resource should not include Exists function
```
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by teddylear**
#566  Description

- Resolved most issues. Two were skipped. One where the linter error didn't need to be resolved in a test case with no user impact for using provider. Other was a change on a resource that will be deprecated the next major release per existing notes. 

### Acceptance tests
- No outstanding tfproviderlint issues
### References
This is related to issue [533](https://github.com/hashicorp/terraform-provider-helm/issues/533)
Fixes #533

### CODE REVIEW

**Comment by teddylear** [comment]
@aareet Is there some issue with the container the tests run in? It looks like the container failed to startup before executing any tests. Not sure where to debug from here without any more information.

**Comment by aareet** [comment]
Oh that's an unrelated failure because we migrated our documentation from terraform.io to registry.terraform.io - it should be fixed alongside the other test fixed we have queued up

**Comment by teddylear** [comment]
@aareet That makes sense. Is there anything else I have to do for this to be merged? Or wait until the tests get updated?

**Comment by aareet** [comment]
Nothing more for now - once we have finished the test infra work, I'll run the full suite on this PR (and the k8s one) and share any failures. Usually if it all passed locally, there shouldn't be any issues on the full suite.

**Comment by teddylear** [comment]
@aareet Is there any update on the test infra work? Is there anything I can help with on that front?

**Comment by aareet** [comment]
@teddylear we're working on https://github.com/hashicorp/terraform-provider-kubernetes/pull/968, amongst other improvements. Appreciate the offer, but it's just a matter of us getting through the various tasks required.

**Comment by teddylear** [comment]
@aareet  Looks like tests are now passing after the other PR was merged.

**Comment by aareet** [comment]
Great, thanks @teddylear , I'll put this back in queue

**Comment by teddylear** [comment]
Should I do the same thing I'm doing with the kubernetes provider and make a separate issue for adding the tfproviderlint to the CI builds/ makefile?

**Comment by aareet** [comment]
Yes I think that's best - we did add some linting recently in this provider via an external contributor so would need to check if tfproviderlint is already in the PR checks list.

**Pull request closed without merging**
