### PR TITLE
Upgrade Helm to v2.16.1 and Kubernetes to v1.16.2

### PR DESCRIPTION
**Pull request by JulienBreux**
Hello world 👋

I think that's requested soon by the community.

Here, two upgrades :
* [Helm v2.16.1](https://github.com/helm/helm/releases/tag/v2.16.1)
* [Kubernetes 1.16.2](https://github.com/kubernetes/kubernetes/releases/tag/v1.16.2)

---

## Be careful 

It's the last version of Kubernetes deps collection.

---

## Note

With the new version of Kubernetes, I must use `replace` 😒
If you've a better way, I'll take it with pleasur 🤗 

Sorry for big `vendor/` changes apply by `go mod vendor`.

### CODE REVIEW

**Comment by karuppiah7890** [comment]
We could wait and change it to v2.16.1 due to this https://github.com/fishworks/fish-food/pull/458#issuecomment-551162195

For now put this as a draft PR / WIP PR

**Comment by alexsomesan** [comment]
Looks like it's best to wait for v2.16.1

**Comment by JulienBreux** [comment]
@alexsomesan ✅ Done 😊

**Comment by JulienBreux** [comment]
> Looks like it's best to wait for v2.16.1

15 days after, any news?

Have a good day.

**Comment by greglanthier** [comment]
I'd like to +1 this issue.

Since 1.16 has [removed deprecated](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/) `apps/v1beta*` `Deployment` resources the current `terraform-provider-helm` plugin won't work for us when we need to create 1.16 clusters.

We have been using `terraform` to provision Kubernetes clusters at work but until the `terraform-provider-helm` plugin uses an updated helm client we need to use a number of workarounds for deploying Helm resources.

**Comment by paaloeye** [comment]
Thank you @JulienBreux for this change. I'd like it being merged as soon as possible.

Is there anything that should be taken care of before merging this issue? @mcuadros @meyskens @alexsomesan @rporres

**Comment by michael-barker** [comment]
Any updates on when this will be available?

**Comment by JulienBreux** [comment]
I'm available for any questions 🤗

**Comment by aaronmell** [comment]
@JulienBreux This should be reopened against the helm v2 branch.

**Comment by mcuadros** [comment]
As described on the README.md, the master is based on Helm 3 for a few months, and we are not accepting any enhancement for branches supporting Helm 2. If this is relevant to Helm 3, and anyone is interested in continuing this work, please open a new pull request.

**Pull request closed without merging**
