### PR TITLE
Upgrade Helm to 3.7.1

### PR DESCRIPTION
**Pull request by okgolove**
### Description

Bump Helm version to 3.7.0

### Acceptance tests
- [ ] Have you added an acceptance test for the functionality being added?

### Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-helm/blob/main/CHANGELOG.md):

```release-note
* Upgrade helm to 3.7.0
```
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### CODE REVIEW

**Comment by tavlima** [comment]
Any reason not to upgrade to 3.7.1, instead?

**Comment by okgolove** [comment]
@tavlima it'd be great if someone reviewed at least this 3.7.0 PR :D

**Comment by jrhouston** [comment]
Thanks for doing this @okgolove – I've pushed an update with 3.7.1. We also had to add the wait option to the uninstall operation, which was introduced in 3.7.0.

**Comment by jrhouston** [comment]
We had to update the Go version in GitHub actions as one of the dependencies brought in io/fs which is 1.16+ only.

**Pull request merged**
