### PR TITLE
Run acceptance tests on travis

### LINKED ISSUE #144: Add acceptance tests to CI pipeline
Currently we use Travis CI to run basic tests and formatting tests but we currently do not run acceptance tests automatically.
Since this provider only depends on having a Kubernetes cluster available we can easily [run minikube inside Travis CI](https://blog.travis-ci.com/2017-10-26-running-kubernetes-on-travis-ci-with-minikube) and run these in a separate build stage (probably only on master).

### PR DESCRIPTION
**Pull request by meyskens**
Fixes  #144

### CODE REVIEW

**Comment by meyskens** [comment]
They seem to take too long for travis to run them it seems.
@alexsomesan what is used usually to run these? Preferably where we can see the results

**Comment by alexsomesan** [comment]
Hi @meyskens, sorry for the delay.

Here is the entire Travis run log: https://api.travis-ci.org/v3/job/453004627/log.txt
I'm trying to determine if there's an option for external contributors to access Travis directly. I'll get back to you on that.

**Comment by alexsomesan** [comment]
@meyskens I just checked. You should be able to access the test logs in Travis.
Are you able to access this one? https://travis-ci.org/terraform-providers/terraform-provider-helm/jobs/453004627

**Comment by meyskens** [comment]
@alexsomesan oh sorry i am totally able to see that! For some reason i remembered that it timed out, maybe the live run did not show the correct output. Thanks!

**Comment by meyskens** [comment]
Should be retested with #166

**Comment by meyskens** [comment]
Tests now run in ~30 minutes which is well within the allowed run time of Travis.
They now also pass thanks to other PRs fixing them.

**Review by rporres — APPROVED** [review]

**Pull request merged**
