### PR TITLE
feat: terraform import resources

### PR DESCRIPTION
**Pull request by caarlos0**
as #150 seems abandoned, I merged master with it and I'm trying to get it done...

@Lemmons if you decide to continue with your PR, feel free to cherry-pick or just ignore :D

### CODE REVIEW

**Comment by caarlos0** [comment]
can someone help me fixing the tests?

**Comment by caarlos0** [comment]
FWIW I used this patch to import everything from 4 kubernetes clusters and everything worked as expected... 

I need to help with the tests (I didn't quite understand why it's failing) and polish up whatever is needed to get this in :)

**Comment by colinhoglund** [comment]
> I need to help with the tests (I didn't quite understand why it's failing) and polish up whatever is needed to get this in :)

I'm not super familiar with these tests, but it would appear most of the failures are due to not having an `id` prefixed with a chart repository on import (ie: `repo/release-id`), which is throwing https://github.com/terraform-providers/terraform-provider-helm/blob/22bc6f6bc5f8b5f1bba502193a5d9a5b1fe7df14/helm/resource_release.go#L511.

**Comment by relu** [comment]
Here's a quick implementation I did for work being done on the Helm v3 provider support (it lacks tests but I'm hoping it might be useful at least as a reference). I managed to test this out with a few releases and it seems to work just fine but I didn't go through more complex use cases.

https://github.com/relu/terraform-provider-helm/tree/dev-v3-import

**Comment by colinhoglund** [comment]
Hey @meyskens, would you mind providing some feedback on this PR? I think this might be blocking some people that can't easily import existing helm releases into terraform state from adopting this tool (myself included). Thanks!

**Comment by abatilo** [comment]
Looking to follow up here. Is there anything that can be done to help push this through? I worry that we're going to get into a state where we don't patch this for current helm2 users who are trying to TF out their charts.

**Comment by artburkart** [comment]
Does this PR handle releases from a local chart where there is no namespace?

**Comment by mcuadros** [comment]
@caarlos0 can you rebase this PR, I have some to review it.

**Comment by legal90** [comment]
Just to notice: the import feature was already implemented in https://github.com/terraform-providers/terraform-provider-helm/pull/394

**Comment by mcuadros** [comment]
Closed by #394

**Pull request closed without merging**
