### PR TITLE
Use GetOkExists instead of GetOk for boolean attributes

### PR DESCRIPTION
**Pull request by osdemah**
Workaround for #303

### CODE REVIEW

**Comment by gordonbondon** [comment]
This is also needed to fix #195

**Comment by selslack** [comment]
@radeksimko @alexsomesan Can we get this moving, please?

**Comment by pierresteiner** [comment]
We would also love if this one could get fixed soon

**Review by meyskens — APPROVED** [review]

**Comment by meyskens** [comment]
Sorry for the delay, thanks for the PR merging this.

**Pull request merged**
