### PR TITLE
Support setting repository password from an environment variable

### PR DESCRIPTION
**Pull request by ksvladimir**
### Description

This tiny PR makes it much easier to use the helm provider with GKE and an OCI repo in Google Artifacts Registry - especially when running in terraform cloud. Instead of adding yet another variable to pass secrets to the helm_release resource, this PR allows simply re-using the environment variable that already exists and is required by the google provider:

```
resource "helm_release" "test" {
  ...

  repository_username = "_json_key"
  repository_password_env = "GOOGLE_CREDENTIALS"
}
```

This has several advantages:

- no need to define another tf variable with the secret and potentially pass it through several layers of modules
- fewer sensitive variables - which reduces the risk of someone forgetting to annotate variables as sensitive
- this is consistent with how most other providers allow passing secrets through environment variables

### Acceptance tests
- [x] Have you added an acceptance test for the functionality being added?

### Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-helm/blob/main/CHANGELOG.md):

```release-note
* Adds the following parameters to the provider
    * repository_password_env - (Optional) Name of an environment variable that holds the password for HTTP basic authentication against the reposotory.
```
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### CODE REVIEW

**Comment by n-oden** [comment]
Is there any chance of getting this merged?  I believe it at least in part addresses https://github.com/hashicorp/terraform-provider-helm/issues/906

**Comment by n-oden** [comment]
This is probably redundant now that https://github.com/hashicorp/terraform-provider-helm/pull/862 is merged and released?

**Comment by cunningr** [comment]
I struggling to use this.  i am trying to use the following pattern:

```
  data "aws_ecr_authorization_token" "token" {}
  provider "helm" {
    kubernetes {
      config_path    = "eks.kube"
      config_context = "default"
    }
    registry {
      url = "oci://ACCOUNTNUMBER.dkr.ecr.us-east-1.amazonaws.com"
      username = data.aws_ecr_authorization_token.token.user_name
      password = data.aws_ecr_authorization_token.token.password
    }
  }
```

But as we are using (sub)modules we need to set the providers in the root module.  The root module has multiple, aliased, AWS providers.  How do I instruct `data "aws_ecr_authorization_token" "token" {}` to use a specific AWS provider alias/profile?

**Comment by BBBmau** [comment]
Thanks for opening this PR! I'll be closing this though since as mentioned by @n-oden, we have this feature merged and released with #862

**Pull request closed without merging**
