### PR TITLE
Helm v3.1.1

### PR DESCRIPTION
**Pull request by relu**
Upgrade helm to v3.1.1

According to the release notes, v3.1.0 comes with the following new features:
- Introduces a new "description" release attribute
- Implements post-rendering support

### CODE REVIEW

**Comment by aaronmell** [comment]
LGTM

**Review by aaronmell — APPROVED** [review]
LGTM

**Comment by evgmoskalenko** [comment]
@jrhouston , review please this changes

**Comment by mgar** [comment]
@relu I opened this PR relu/terraform-provider-helm#1 against your branch to add a new flag that was introduced in Helm v3.1.0 [here](https://github.com/helm/helm/commit/67e57a5fbb7b210e534157b8f67c15ffc3445453)

Would you please merge it into your branch?

**Comment by relu** [comment]
> @relu I opened this PR [relu#1](https://github.com/relu/terraform-provider-helm/pull/1) against your branch to add a new flag that was introduced in Helm v3.1.0 [here](https://github.com/helm/helm/commit/67e57a5fbb7b210e534157b8f67c15ffc3445453)
> 
> Would you please merge it into your branch?

Great! Looks like I missed that one :)

**Comment by jrhouston** [comment]
Need to resolve those conflicts, otherwise LGTM.

**Review by jrhouston — APPROVED** [review]

**Pull request merged**
