### PR TITLE
update helm to v2.15.2

### LINKED ISSUE #370: Update helm to v2.16.1
Currently helm v2.15.1 is being used

Latest version is v2.16.0 - https://github.com/helm/helm/releases/tag/v2.16.0 (as of now)

But it's preferred to wait and use v2.16.1 due to this https://github.com/fishworks/fish-food/pull/458#issuecomment-551162195

### PR DESCRIPTION
**Pull request by karuppiah7890**
Fixes #370

### CODE REVIEW

**Comment by karuppiah7890** [comment]
Just a heads up, 2.16.0-rc.1 has also been released

**Review by JulienBreux — APPROVED** [review]
LGTM 👍

**Comment by JulienBreux** [comment]
> Just a heads up, 2.16.0-rc.1 has also been released

Yes, but we must wait for the stable 2.16.x. 😊

**Comment by karuppiah7890** [comment]
Updating helm to 2.16.0 as the stable has been released https://github.com/helm/helm/releases/tag/v2.16.0

**Comment by JulienBreux** [comment]
🔗 Related https://github.com/terraform-providers/terraform-provider-helm/pull/373

**Comment by karuppiah7890** [comment]
Actually I was hoping to do it in this PR 😕 But anyways, will close this one...

**Comment by JulienBreux** [comment]
@karuppiah7890 Erf, I'm sorry and confused :/

**Pull request closed without merging**
