### PR TITLE
Fix CRD template with multi docs and output CRDs as a separate output

### LINKED ISSUE #791: Output CRDs separate from manifests
### Description

Currently the `helm_template` datasource will pass the rendered manifests through the two outputs `manifest` and `manifests`. The difference being that one is a multipart yaml while the other is a map containing each individual file. With the optional variable `include_crds` the contents of the CRD directory in the helm chart will be added to the outputs, this variable is false by default.

Helm has made an active choice to not manage CRD upgrades if the CRD already exists in the cluster. Instead it is up to the end user to manage this, which is not optimal with large amounts of clusters. Instead this should be possible to automate, preferably with existing maintained providers.

One option is that the `helm_template` datasource adds a new output called `crds` which is a map with all of the CRDs only. This would make it possible to make use of other provider such as [terraform-provider-kubectl](https://registry.terraform.io/providers/gavinbunney/kubectl/latest/docs) to apply the manifests before the Helm chart is installed.

### Potential Terraform Configuration

```hcl
data "helm_template" "opa_gatekeeper" {
  repository = "https://open-policy-agent.github.io/gatekeeper/charts"
  chart      = "gatekeeper"
  version    = "3.6.0"
  name       = "gatekeeper"
}

resource "kubectl_manifest" "opa_gatekeeper_crd" {
  for_each = data.helm_template.opa_gatekeeper.crds
  yaml_body  = each.value
}

```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by phillebaba**
### Description

This change fixes a long running issue and implements a related feature at the same time. The issue #782 describes the weird behavior in the Helm template datasource when a Helm chart includes a crds directory, and the CRDs start with a multidoc yaml annotation `---`. The current version of this provider is not able to deal with this, due to the way Helm works. Helm treats yaml in the templates and crds directory differently. Any extra multidoc annotation in the templates directory is sanitized and removed, bu that is not the case for yaml in the crds directory.

This PR changes to get the CRDs from the chart instead of having the template command do it. Then the CRDs are appended before computing the output parameters. This also enables the possibility to output the CRDs separatly from the manifests. An additional change is the addition of two outputs from the datasource which mimic the manifest output but only include the CRDs.

### Acceptance tests
- [x] Have you added an acceptance test for the functionality being added?

### Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-helm/blob/main/CHANGELOG.md):

```release-note
* Add `crds` and `crd` outputs to `helm_template` datasource
* Fix templating of crds in `helm_template` datasource when CRDs contain multidoc yaml annotations
```
### References

Fixes #791 #782 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### CODE REVIEW

**Comment by phillebaba** [comment]
@jrhouston this change became a bit bigger than I wanted it to be, but the refactoring was necessary to be able to do the separate CRD outputs.

**Comment by phillebaba** [comment]
Any update on getting this merged?

**Comment by phillebaba** [comment]
Ping for the new year.

**Comment by niccrane** [comment]
Any updates on when this will be merged? Thanks!

**Comment by phillebaba** [comment]
@jrhouston could we get this merged?

**Comment by MatthiasWinzeler** [comment]
@phillebaba @jrhouston any chance to get this merged?

I think you'll be doing the community a huge favour - currently, there is no way to selectively install only CRDs and the landscape with helm charts is a mess regarding CRDs not being updated by helm.

**Comment by aidanmelen** [comment]
Hello Mr.@jrhouston. Could you please take a look at this feature request? I am sure the community would appreciate it.

**Comment by robinkb** [comment]
Hi @jrhouston , I am one of the many people looking for this feature. Can you please give us an update on the state of this PR? Does it need some code changes? Is it ready to merge in? I would love to do the work to get this resolved and into the provider.

**Comment by dhoeld** [comment]
I guess this is fixed by the PR https://github.com/hashicorp/terraform-provider-helm/pull/1050 which has been released yesterday in release [v2.9.0](https://github.com/hashicorp/terraform-provider-helm/releases/tag/v2.9.0).

I tested it using the example code below:
```terraform
data "helm_template" "kube_prometheus_stack" {
  name       = "kube-prometheus-stack"
  namespace  = "kube-prometheus-stack"
  repository = "https://prometheus-community.github.io/helm-charts"

  chart   = "kube-prometheus-stack"
  version = "45.1.0"

  include_crds = true
}

resource "kubernetes_manifest" "crds" {
  for_each = toset(data.helm_template.kube_prometheus_stack.crds)
  manifest = yamldecode(each.value)
}
```

**Pull request closed without merging**
